<WireTest@BGTemplate>
    size: cm(5), cm(5)
    WireField:
        points: 0,0, 100/cm(5),100/cm(5),100/cm(5),50/cm(5),50/cm(5),100/cm(5)
        size: root.size
        bg_color: 0,0,1,1
        line_color: 0,1,0,1
        id: wire

<BezierTest@BGTemplate>
    size: cm(5), cm(5)
    BezierField:
        points: 0,0, 100/cm(5),100/cm(5),100/cm(5),50/cm(5),50/cm(5),100/cm(5)
        size: root.size
        bg_color: 0,0,1,1
        line_color: 0,1,0,1
        id: wire