<Zindex@BGTemplate>:
	size: 100, 100


	TextField:
		text: "bottom"
		size: 240.00, 333
		valign: "middle"
		autofit: True
		id: bottom
		font_size: 74.00
		halign: "center"
		bg_color: 1,0,0,1
		z: 1


	TextField:
		bg_color: 0,1,0,1
		text: "above"
		size: 240.00, 333
		valign: "middle"
		autofit: True
		id: above
		font_size: 89.00
		halign: "center"
		z: 2
		default_attr: 'z'

